# Generated by Django 5.1.1 on 2024-12-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='groundId',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='selectedSlots',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Payment ID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='signature',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Signature'),
        ),
    ]
