# Generated by Django 5.1.1 on 2024-12-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_transaction_groundid_transaction_selectedslots_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount_due',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Amount Due'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Amount Paid'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='attempts',
            field=models.IntegerField(default=0, verbose_name='Attempts'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='', max_length=10, verbose_name='Currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='', max_length=20, verbose_name='Status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='order_id',
            field=models.CharField(max_length=200, verbose_name='Order ID'),
        ),
    ]
