# Generated by Django 5.1.1 on 2024-12-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_transaction_amount_due_transaction_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='ground_booked_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
