# Generated by Django 5.1.1 on 2024-12-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_transaction_ground_booked_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.CharField(default='', max_length=200, verbose_name='User'),
            preserve_default=False,
        ),
    ]
