# Generated by Django 5.1.1 on 2024-12-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='message',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
