# Generated by Django 5.1.1 on 2024-12-21 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grounds', '0012_alter_groundnew_unique_together_and_more'),
        ('payments', '0009_transaction_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='groundId',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='grounds.groundnew', verbose_name='Ground ID'),
        ),
    ]
