# Generated by Django 5.1.1 on 2025-01-03 21:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_alter_transaction_groundid'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='slotDates',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Slot selected Date'),
            preserve_default=False,
        ),
    ]
