# Generated by Django 5.1.1 on 2025-01-04 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_transaction_slotdates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='slotDates',
        ),
    ]
