# Generated by Django 5.1.1 on 2025-05-09 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_remove_transaction_slotdates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='ground_booked_date',
            new_name='booked_date',
        ),
    ]
