# Generated by Django 5.1.1 on 2025-05-09 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_rename_ground_booked_date_transaction_booked_date'),
        ('tournament', '0011_alter_teams_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tournament',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament', verbose_name='Tournament'),
        ),
    ]
