# Generated by Django 5.1.1 on 2025-05-18 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_transaction_tournament'),
        ('tournament', '0014_alter_matchscore_teams_alter_tournament_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='team',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.teams', verbose_name='Tournament'),
        ),
    ]
