# Generated by Django 5.0.4 on 2025-12-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_transaction_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='order_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='Order ID'),
        ),
    ]
