# Generated by Django 5.1.1 on 2025-05-04 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_tournament_end_date_tournament_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='start_time',
        ),
    ]
