# Generated by Django 5.1.1 on 2025-05-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grounds', '0012_alter_groundnew_unique_together_and_more'),
        ('tournament', '0003_remove_tournament_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='ground',
        ),
        migrations.AddField(
            model_name='tournament',
            name='ground',
            field=models.ManyToManyField(to='grounds.groundnew'),
        ),
    ]
