# Generated by Django 5.1.1 on 2025-05-05 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_remove_tournament_ground_tournament_ground'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='CreatedBy',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='Created',
            new_name='created_date',
        ),
    ]
