# Generated by Django 5.1.1 on 2025-05-05 09:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_tournament_updated_by_tournament_updated_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
