# Generated by Django 5.1.1 on 2025-05-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
