# Generated by Django 5.1.1 on 2025-05-07 18:09

import tournament.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0009_tournament_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='id',
            field=models.CharField(default=tournament.models.GenTournamentId, max_length=50, primary_key=True, serialize=False),
        ),
    ]
