# Generated by Django 5.1.1 on 2025-05-07 18:37

import tournament.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0010_alter_tournament_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='id',
            field=models.CharField(default=tournament.models.GenTeamId, max_length=50, primary_key=True, serialize=False),
        ),
    ]
