# Generated by Django 5.1.1 on 2025-05-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0011_alter_teams_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='teams',
            field=models.ManyToManyField(blank=True, null=True, to='tournament.teams'),
        ),
    ]
