# Generated by Django 5.1.1 on 2025-05-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0013_matchscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchscore',
            name='teams',
            field=models.ManyToManyField(blank=True, to='tournament.teams'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='teams',
            field=models.ManyToManyField(blank=True, to='tournament.teams'),
        ),
    ]
