# Generated by Django 5.0.4 on 2025-06-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0014_alter_matchscore_teams_alter_tournament_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='match_schedule_image',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
