# Generated by Django 5.0.4 on 2025-06-15 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grounds', '0012_alter_groundnew_unique_together_and_more'),
        ('tournament', '0016_remove_matchscore_grounds_matchscore_tournament'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchscore',
            name='teams',
        ),
        migrations.AddField(
            model_name='matchscore',
            name='grounds',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grounds.groundnew'),
        ),
        migrations.AddField(
            model_name='matchscore',
            name='team1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='tournament.teams'),
        ),
        migrations.AddField(
            model_name='matchscore',
            name='team2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='tournament.teams'),
        ),
    ]
