# Generated by Django 5.0.4 on 2025-07-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0017_remove_matchscore_teams_matchscore_grounds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='game',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
