# Generated by Django 5.0.4 on 2025-08-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0018_tournament_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='team_logo/'),
        ),
    ]
