# Generated by Django 5.0.4 on 2025-12-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0020_matches'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='registered_count',
            field=models.IntegerField(default=0),
        ),
    ]
