# Generated by Django 5.0.4 on 2025-12-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0021_tournament_capacity_tournament_registered_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='price_pool',
            field=models.IntegerField(default=0),
        ),
    ]
