# Generated by Django 5.0.4 on 2025-12-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0022_tournament_price_pool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='price',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
