# Generated by Django 5.0.4 on 2025-12-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0024_alter_tournament_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
