# Generated by Django 5.0.4 on 2025-12-21 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0025_alter_tournament_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='tournament.teams'),
        ),
    ]
