# Generated by Django 5.0.4 on 2025-12-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0026_matches_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='venue',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
