# Generated by Django 5.1.1 on 2024-10-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_sitemanagement_slideshow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemanagement',
            name='slideshow',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
