# Generated by Django 5.1.1 on 2024-10-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_sitemanagement_slideshow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitemanagement',
            name='logo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
