# Generated by Django 5.1.1 on 2024-10-08 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_myuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
