# Generated by Django 5.1.1 on 2024-11-05 08:37

import datetime
import django.core.validators
import django.db.models.deletion
import grounds.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=150)),
                ('ground_type', models.CharField(max_length=150)),
                ('capacity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('surface_type', models.CharField(max_length=250)),
                ('availability_status', models.BooleanField(default=False)),
                ('ground_images', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'db_table': 'arena',
            },
        ),
        migrations.CreateModel(
            name='Grounds',
            fields=[
                ('id', models.CharField(default=grounds.models.GenGroundId, max_length=50, primary_key=True, serialize=False)),
                ('ground_name', models.CharField(max_length=500)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('locker_room', models.BooleanField(default=False)),
                ('wash_rooms', models.BooleanField(default=False)),
                ('lighting_night', models.BooleanField(default=False)),
                ('parking_facility', models.BooleanField(default=False)),
                ('scoreboard', models.BooleanField(default=False)),
                ('scoreboard_type', models.CharField(blank=True, choices=[('Digital', 'Digital'), ('Manual', 'Manual'), ('Not Avaliable', 'Not Avaliable')], default=None, max_length=20, null=True)),
                ('last_maintenance_date', models.DateTimeField(blank=True, null=True)),
                ('next_maintenance_date', models.DateTimeField(blank=True, null=True)),
                ('maintenance_status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Pending', 'Pending'), ('Not Scheduled', 'Not Scheduled')], max_length=20)),
                ('maintenance_team_contact', models.CharField(max_length=200)),
                ('Arena', models.JSONField(blank=True, default=dict, null=True)),
                ('address', models.JSONField(blank=True, default=dict, null=True)),
                ('created', models.DateTimeField(default=datetime.datetime(2024, 11, 5, 14, 7, 6, 902502))),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'grounds',
            },
        ),
    ]
