# Generated by Django 5.1.1 on 2024-10-01 04:24

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grounds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locker_rooms', models.BooleanField(default=False)),
                ('washrooms', models.BooleanField(default=False)),
                ('lighting', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('scoreboard', models.BooleanField(default=False)),
                ('scoreboard_type', models.CharField(blank=True, choices=[('Digital', 'Digital'), ('Manual', 'Manual')], default=None, max_length=20, null=True)),
                ('created', models.DateTimeField(default=datetime.datetime(2024, 10, 1, 9, 54, 47, 225156))),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'grounds',
            },
        ),
    ]
