# Generated by Django 5.1.1 on 2024-11-05 08:42

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grounds', '0002_alter_grounds_created'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroundManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GroundName', models.CharField(max_length=250)),
                ('VenueName', models.CharField(max_length=250)),
                ('GroundDescription', models.TextField(blank=True, null=True)),
                ('Location', models.CharField(max_length=250)),
                ('Promotions', models.JSONField(blank=True, default=dict, null=True)),
                ('Images', models.JSONField(blank=True, default=dict, null=True)),
                ('ManagePrice', models.JSONField(blank=True, default=dict, null=True)),
                ('Amenities', models.JSONField(blank=True, default=dict, null=True)),
                ('AboutVenue', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(default=datetime.datetime(2024, 11, 5, 14, 12, 3, 855138))),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ground_management',
                'unique_together': {('GroundName', 'VenueName', 'Location')},
            },
        ),
        migrations.DeleteModel(
            name='Arena',
        ),
        migrations.AlterField(
            model_name='grounds',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 5, 14, 12, 3, 855138)),
        ),
    ]
