# Generated by Django 5.1.1 on 2024-11-05 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grounds', '0003_groundmanagement_delete_arena_alter_grounds_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groundmanagement',
            old_name='created_by',
            new_name='CreatedBy',
        ),
        migrations.RemoveField(
            model_name='groundmanagement',
            name='created',
        ),
        migrations.AddField(
            model_name='groundmanagement',
            name='GroundContact',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='grounds',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 5, 16, 23, 50, 319084)),
        ),
        migrations.AddField(
            model_name='groundmanagement',
            name='Created',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 5, 16, 23, 50, 320083)),
        ),
    ]
