# Generated by Django 5.1.1 on 2024-10-03 04:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grounds', '0004_alter_grounds_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grounds',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 3, 9, 47, 6, 207847)),
        ),
        migrations.AlterField(
            model_name='grounds',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
