# Generated by Django 5.1.1 on 2024-11-05 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grounds', '0004_rename_created_by_groundmanagement_createdby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groundmanagement',
            name='Created',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 5, 16, 24, 11, 958112)),
        ),
        migrations.AlterField(
            model_name='grounds',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 5, 16, 24, 11, 958112)),
        ),
    ]
