# Generated by Django 5.1.1 on 2024-11-05 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grounds', '0005_alter_groundmanagement_created_alter_grounds_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groundmanagement',
            name='Created',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 5, 22, 0, 59, 780853)),
        ),
        migrations.AlterField(
            model_name='grounds',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 5, 22, 0, 59, 780853)),
        ),
    ]
