# Generated by Django 5.1.1 on 2024-11-05 16:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grounds', '0006_alter_groundmanagement_created_alter_grounds_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groundmanagement',
            name='Created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='grounds',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
