# Generated by Django 5.1.1 on 2024-10-03 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grounds', '0006_grounds_active_alter_grounds_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grounds',
            old_name='active',
            new_name='is_active',
        ),
        migrations.AlterField(
            model_name='grounds',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 3, 13, 56, 54, 768344)),
        ),
    ]
