# Generated by Django 5.1.1 on 2024-11-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grounds', '0007_alter_groundmanagement_created_alter_grounds_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='groundmanagement',
            name='maintenance',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
