# Generated by Django 5.1.1 on 2024-10-04 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grounds', '0007_rename_active_grounds_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grounds',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 4, 11, 4, 25, 27875)),
        ),
    ]
