# Generated by Django 5.1.1 on 2024-11-15 03:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import grounds.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grounds', '0008_groundmanagement_maintenance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroundNew',
            fields=[
                ('id', models.CharField(default=grounds.models.GenGroundIds, max_length=50, primary_key=True, serialize=False)),
                ('ground_name', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('venue', models.CharField(blank=True, max_length=500, null=True)),
                ('type', models.CharField(max_length=250)),
                ('capacity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('contact_number', models.CharField(blank=True, max_length=250, null=True)),
                ('images', models.JSONField(blank=True, default=dict, null=True)),
                ('promotions', models.JSONField(blank=True, default=dict, null=True)),
                ('maintenanceSchedule', models.JSONField(blank=True, default=dict, null=True)),
                ('pricing', models.JSONField(blank=True, default=dict, null=True)),
                ('amenities', models.JSONField(blank=True, default=list, null=True)),
                ('groundRulesInfo', models.JSONField(blank=True, default=dict, null=True)),
                ('Created', models.DateTimeField(default=django.utils.timezone.now)),
                ('CreatedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ground_new',
                'unique_together': {('ground_name', 'name', 'venue', 'location')},
            },
        ),
    ]
