# Generated by Django 5.1.1 on 2024-11-28 18:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grounds', '0010_groundnew_availability_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='groundnew',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='groundnew',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
