# Generated by Django 5.1.1 on 2024-11-28 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grounds', '0011_groundnew_address_alter_groundnew_location'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groundnew',
            unique_together={('ground_name', 'name', 'address', 'location')},
        ),
        migrations.RemoveField(
            model_name='groundnew',
            name='venue',
        ),
    ]
