# Generated by Django 5.1.1 on 2024-10-08 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grounds', '0016_alter_grounds_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grounds',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 8, 21, 41, 17, 442863)),
        ),
    ]
