# Generated by Django 5.1.1 on 2024-10-19 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grounds', '0025_alter_grounds_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='grounds',
            name='last_maintenance_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grounds',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='grounds',
            name='maintenance_status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Pending', 'Pending'), ('Not Scheduled', 'Not Scheduled')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grounds',
            name='next_maintenance_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grounds',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 19, 16, 11, 53, 689970)),
        ),
    ]
