# Generated by Django 5.1.1 on 2024-10-19 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grounds', '0026_grounds_last_maintenance_date_grounds_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grounds',
            name='Arena',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='grounds',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 19, 16, 24, 23, 191906)),
        ),
    ]
