# Generated by Django 5.1.1 on 2024-10-19 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grounds', '0027_grounds_arena_alter_grounds_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='grounds',
            name='ground_images',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='grounds',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 19, 16, 26, 0, 930877)),
        ),
    ]
