# Generated by Django 5.1.1 on 2024-10-20 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grounds', '0028_grounds_ground_images_alter_grounds_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grounds',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 20, 17, 32, 21, 159528)),
        ),
    ]
