# Generated by Django 5.1.1 on 2024-10-21 08:23

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grounds', '0029_alter_grounds_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='grounds',
            name='capacity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='grounds',
            name='game',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grounds',
            name='ground_type',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grounds',
            name='surface_type',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grounds',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 21, 13, 53, 35, 192659)),
        ),
        migrations.AlterField(
            model_name='grounds',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
