# Generated by Django 5.1.1 on 2024-10-21 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grounds', '0030_grounds_capacity_grounds_game_grounds_ground_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grounds',
            old_name='name',
            new_name='ground_name',
        ),
        migrations.RemoveField(
            model_name='grounds',
            name='Arena',
        ),
        migrations.RemoveField(
            model_name='grounds',
            name='ground_type',
        ),
        migrations.AlterField(
            model_name='grounds',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 21, 14, 2, 25, 911746)),
        ),
    ]
