# Generated by Django 5.1.1 on 2024-10-22 04:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grounds', '0031_rename_name_grounds_ground_name_remove_grounds_arena_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grounds',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='grounds',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 22, 9, 49, 4, 616050)),
        ),
    ]
