# Generated by Django 5.1.1 on 2024-10-22 04:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grounds', '0032_remove_grounds_is_active_alter_grounds_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='grounds',
            name='management_contact',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grounds',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 22, 9, 55, 18, 594391)),
        ),
    ]
