# Generated by Django 5.1.1 on 2024-10-22 04:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grounds', '0033_grounds_management_contact_alter_grounds_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grounds',
            old_name='management_contact',
            new_name='maintenance_team_contact',
        ),
        migrations.AlterField(
            model_name='grounds',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 22, 9, 56, 49, 385581)),
        ),
    ]
