# Generated by Django 5.1.1 on 2024-10-23 04:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grounds', '0034_rename_management_contact_grounds_maintenance_team_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grounds',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 23, 10, 5, 39, 100541)),
        ),
        migrations.AlterField(
            model_name='grounds',
            name='game',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='grounds',
            name='surface_type',
            field=models.CharField(default='', max_length=250),
        ),
    ]
