# Generated by Django 5.1.1 on 2024-10-23 04:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grounds', '0035_alter_grounds_created_alter_grounds_game_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grounds',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 23, 10, 7, 45, 63087)),
        ),
        migrations.AlterField(
            model_name='grounds',
            name='game',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='grounds',
            name='surface_type',
            field=models.CharField(max_length=250),
        ),
    ]
