# Generated by Django 5.1.1 on 2024-10-23 06:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grounds', '0037_alter_grounds_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grounds',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 23, 12, 22, 28, 576147)),
        ),
        migrations.AlterField(
            model_name='grounds',
            name='maintenance_status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Pending', 'Pending'), ('Not Scheduled', 'Not Scheduled')], max_length=20),
        ),
    ]
