# Generated by Django 5.1.1 on 2024-10-23 06:56

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grounds', '0039_remove_grounds_address_remove_grounds_ground_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grounds',
            name='availability_status',
        ),
        migrations.RemoveField(
            model_name='grounds',
            name='lighting_night',
        ),
        migrations.RemoveField(
            model_name='grounds',
            name='locker_room',
        ),
        migrations.RemoveField(
            model_name='grounds',
            name='parking_facility',
        ),
        migrations.RemoveField(
            model_name='grounds',
            name='wash_rooms',
        ),
        migrations.AddField(
            model_name='grounds',
            name='address',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='grounds',
            name='ground_images',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='grounds',
            name='lighting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grounds',
            name='locker_rooms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grounds',
            name='parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grounds',
            name='scoreboard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grounds',
            name='washrooms',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='grounds',
            name='capacity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='grounds',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 23, 12, 26, 33, 784449)),
        ),
        migrations.AlterField(
            model_name='grounds',
            name='last_maintenance_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grounds',
            name='maintenance_status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Pending', 'Pending'), ('Not Scheduled', 'Not Scheduled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='grounds',
            name='next_maintenance_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grounds',
            name='scoreboard_type',
            field=models.CharField(blank=True, choices=[('Digital', 'Digital'), ('Manual', 'Manual')], default=None, max_length=20, null=True),
        ),
        migrations.AlterModelTable(
            name='grounds',
            table='grounds',
        ),
    ]
