# Generated by Django 5.1.1 on 2024-10-23 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grounds', '0040_remove_grounds_availability_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grounds',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 23, 14, 16, 32, 629524)),
        ),
    ]
