# Generated by Django 5.1.1 on 2024-10-23 10:06

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grounds', '0043_rename_lighting_grounds_lighting_night_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=150)),
                ('ground_type', models.CharField(max_length=150)),
                ('capacity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('surface_type', models.CharField(max_length=250)),
                ('availability_status', models.BooleanField(default=False)),
                ('ground_images', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'db_table': 'arena',
            },
        ),
        migrations.RemoveField(
            model_name='grounds',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='grounds',
            name='game',
        ),
        migrations.RemoveField(
            model_name='grounds',
            name='ground_images',
        ),
        migrations.RemoveField(
            model_name='grounds',
            name='surface_type',
        ),
        migrations.AlterField(
            model_name='grounds',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 23, 15, 36, 13, 934901)),
        ),
    ]
