# Generated by Django 5.1.1 on 2024-10-23 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grounds', '0044_arena_remove_grounds_capacity_remove_grounds_game_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grounds',
            name='Arena',
            field=models.ManyToManyField(to='grounds.arena'),
        ),
        migrations.AlterField(
            model_name='grounds',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 23, 15, 40, 23, 316674)),
        ),
    ]
