# Generated by Django 5.1.1 on 2024-10-23 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grounds', '0045_grounds_arena_alter_grounds_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grounds',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 23, 17, 35, 13, 233085)),
        ),
        migrations.AlterField(
            model_name='grounds',
            name='scoreboard_type',
            field=models.CharField(blank=True, choices=[('Digital', 'Digital'), ('Manual', 'Manual'), ('Not Avaliable', 'Not Avaliable')], default=None, max_length=20, null=True),
        ),
    ]
