# Generated by Django 5.1.1 on 2024-10-23 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grounds', '0046_alter_grounds_created_alter_grounds_scoreboard_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grounds',
            name='Arena',
            field=models.ManyToManyField(blank=True, null=True, to='grounds.arena'),
        ),
        migrations.AlterField(
            model_name='grounds',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 23, 17, 51, 53, 556766)),
        ),
    ]
