# Generated by Django 5.1.1 on 2024-10-24 03:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grounds', '0047_alter_grounds_arena_alter_grounds_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grounds',
            name='Arena',
        ),
        migrations.AlterField(
            model_name='grounds',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 24, 9, 8, 29, 124599)),
        ),
        migrations.AddField(
            model_name='grounds',
            name='Arena',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
