# Generated by Django 5.1.1 on 2024-10-24 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grounds', '0048_remove_grounds_arena_alter_grounds_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grounds',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 24, 21, 51, 38, 666306)),
        ),
    ]
