# Generated by Django 5.1.1 on 2024-10-25 06:14

import datetime
import grounds.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grounds', '0053_alter_grounds_created_alter_grounds_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grounds',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 25, 11, 44, 55, 961580)),
        ),
        migrations.AlterField(
            model_name='grounds',
            name='id',
            field=models.CharField(default=grounds.models.GenGroundId, max_length=50, primary_key=True, serialize=False),
        ),
    ]
