# Generated by Django 5.1.1 on 2024-10-28 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grounds', '0054_alter_grounds_created_alter_grounds_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grounds',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 28, 17, 28, 39, 414891)),
        ),
    ]
